### ISSUE TITLE
Ability to configure serving from https ssl by default

### ISSUE THREAD

**Issue by chaostheory** [cloudinary/cloudinary_gem#306]
Not sure if this already exists but it would be nice to be able to configure the cloudinary gem to serve everything from https / ssl by default. I am aware of the cl_image_tag, but having this config would be a lot more convenient when using something like CarrierWave.

**Comment by taragano** [comment]
1. The GEM's `cl_image_tag` method will automatically send URLs via HTTPS if the site's protocol is HTTPS too.
2. You can force HTTPS URLs globally by setting so in the cloudinary.yml file, e.g.,:

    ```
    development:
      cloud_name: mycloud
      api_key: '1234567890'
      api_secret: mysecret
      enhance_image_tag: true
      static_image_support: false
      secure: true
      ...
    ```
