### ISSUE TITLE
CloudinaryException (Must supply cloud_name in tag or in configuration)

### ISSUE THREAD

**Issue by radek-polcode** [cloudinary/cloudinary_gem#334]
Hi,` I'm using carrierwave and cloudinary gems to upload files.
Rails 5.2.0 and Ruby 2.5.0.
carrierwave 1.3.1
carrierwave-base64 2.8.0
cloudinary 1.11.1

I have `cloudinary.yml`
```
---
development:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>

production:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
test:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>`
```

config in initialiizers dir:
```
Cloudinary.config do |config|
  config.cloud_name = ENV['CLOUDINARY_CLOUD_NAME']
  config.api_key = ENV['CLOUDINARY_API_KEY']
  config.api_secret = ENV['CLOUDINARY_API_SECRET']
end
```

and `CLOUDINARY_URL` set.

I am attaching also uploader:
```
class PhotoUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  include Cloudinary::CarrierWave

  def public_id
    random_id = Cloudinary::Utils.random_public_id
    case Rails.env
    when 'test'
      "test/#{@model.class.name.downcase}/photo/" + random_id
    when 'development'
      "development/#{@model.class.name.downcase}/photo/" + random_id
    when 'production'
      "production/#{@model.class.name.downcase}/photo/" + random_id
    else
      "all/#{@model.class.name.downcase}/" + random_id
    end
  end

  version :mini do
    resize_to_fit(50, 50)
  end

  version :thumb do
    resize_to_fit(100, 100)
  end

  version :medium do
    resize_to_fit(200, 200)
  end

  def extension_whitelist
    %w(jpg jpeg gif png)
  end

  def content_type_whitelist
    /image\//
  end
end
```

I was able to run the seeds which correctly ran and upload all photos from local app and from EC2 app, they are available in correct dirs on cloudinary.

When I am doing GET request to get resources (to index action which should give me all records with photos) locally working app it's fine 
BUT when I am doing GET to EC2 I am getting `CloudinaryException (Must supply cloud_name in tag or in configuration)`

I checked all envs with printenv, also in rails console on the server, they exist, I also found, that this error in gem is raised in only one line:
` cloud_name = config_option_consume(options, :cloud_name) || raise(CloudinaryException, "Must supply cloud_name in tag or in configuration")
`

method is: 
```  
def self.config_option_consume(options, option_name, default_value = nil)
    return options.delete(option_name) if options.include?(option_name)
    return Cloudinary.config.send(option_name) || default_value
  end
```

I also checked in a rails console `Cloudinary.config.send(:cloud_name)` it gaves me my cloud name correctly.

I stucked a bit. 
Am I missing something? Should I include some `option` in the API call to the server?
