### ISSUE TITLE
secure: true in cloudinary.yml is being overridden

### ISSUE THREAD

**Issue by sairam** [cloudinary/cloudinary_gem#381]
We found some Cloudinary gem is creating `http://` image urls instead of `https://` even though cloudinary.yml has `secure: true` setting. 

In our cloudinary.yml, we are using ENV variables for `CLOUDINARY_CLOUD_NAME` and `CLOUDINARY_API_KEY`, `CLOUDINARY_API_SECRET` and shared ENV keys for `secure_distribution` and `cname`, `secure`. 

cloudinary.yml
```
staging:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secure: <%= ENV["ENABLE_SSL"] == "true" %>
  sign_url: true
  secure_distribution: <%= ENV['CLOUDFRONT_HOST'] %>
  cname: <%= ENV['CLOUDFRONT_HOST'] %>
```
ENABLE_SSL is being set and used for the complete website. After a recent upgrade, we started seeing http urls instead of https URLs. 

```
> Cloudinary.config
# => secure=false, sign_url=true, secure_distribution="XXXXXXXX.cloudfront.net", cname="XXXXXXXX.cloudfront.net"
```

I could trace the issue to here - https://github.com/cloudinary/cloudinary_gem/blob/c105a0acba8a4e446ee409e385686a480fbce0b0/lib/cloudinary.rb#L75

I could find the code is being overriding this for HEROKU to respect all ENV variables if `CLOUDINARY_CLOUD_NAME` is present. Our config does not have `CLOUDINARY_SECURE_DISTRIBUTION`, so, that is not being overridden.

New line should look like:
```ruby
        "secure"              => ENV["CLOUDINARY_SECURE"] ? ENV["CLOUDINARY_SECURE"].to_s == 'true' : nil
```

[old line](https://github.com/cloudinary/cloudinary_gem/blob/c105a0acba8a4e446ee409e385686a480fbce0b0/lib/cloudinary.rb#L75):
```ruby
        "secure"              => ENV["CLOUDINARY_SECURE"].to_s == 'true'
```
