### ISSUE TITLE
`cl_image_tag` and `cloudinary_url` ignores model class `ActiveStorage` service configuration

### ISSUE THREAD

**Issue by motomic-efdezpolo** [cloudinary/cloudinary_gem#557]
## Bug report for Cloudinary Ruby SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
I have different `ActiveStorage` configuration with different folders to organize a little bit my images. The problem is that the SDK it's only getting the service from the global application configuration and not from the model class when present.

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [X] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce
```yaml
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudinary_brands:
  service: Cloudinary
  cloud_name: <%= ENV.fetch("CLOUDINARY_CLOUD_NAME") %>
  api_key: <%= ENV.fetch("CLOUDINARY_API_KEY") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_API_SECRET") %>
  folder: <%= Rails.env + '/brands' %>
  secure: true
```

```ruby
class Brand < ApplicationRecord
  has_one_attached :logo, service: :cloudinary_brands
end
```

```ruby
config.active_storage.service = :local # If I set this to  :cloudinary_brands the URLs are properly generated
```

## Error screenshots or Stack Trace (if applicable)
…

## Operating System
- [ ] Linux
- [ ] Windows
- [ ] macOS
- [X] All

## Environment and Libraries (fill in the version numbers)
- Cloudinary Ruby SDK version - 2.1.2
- Ruby Version - 3.3.4
- Rails Version - 7.2

## Repository

If possible, please provide a link to a reproducible repository that showcases the problem
